### ISSUE TITLE
Migrate plugin parking

### ISSUE THREAD

**Issue by mape2k** [Bytespeicher/Bytebot#121]

**Comment by mape2k** [comment]
Plugin isn't working for now. API-data is unavailable.

**Comment by mape2k** [comment]
@jurkov: Did you know anything about API changes or did you check possibilities for new API? Should i contact the city management to get an (open) API?

**Comment by jurkov** [comment]
Please ask @suicider. He got in contact with the developer of the erfurt parking app. They have a new XML API and we need to get in contact with the city managment. You can find the email addy of the gis admin on the erfurt city map website.

**Comment by suicider** [comment]
Yes, Alex @gruessung, the developer of the parking app, told me he has a contract with the city management. We should arrange who of us will ask them. But in doubt I'll do it. 

Meanwhile take a look at his app: https://github.com/gruessung/ParkenInErfurt/commit/f2a9dc831810a68137eed19ff46eab4a6c113276 :)

**Comment by jurkov** [comment]
I think we should ask as club the city. Maybe we can extend the communication later.

**Comment by suicider** [comment]
I talked with the responsible officer on the town administration and we received the XML file for testing purposes. In the next week I will negotiate the contract and then we may start with the full integration.

**Comment by mape2k** [comment]
Plugin is migrated and uses source direct. We should provide a mirror and use this as soon as possible. Therefor we should agree on how we'll provide the data. For a interim period we can also provide a simple mirror without a website (e.g. on opendata.technikkultur-erfurt.de/raw/parking/erfurt.xml) and simple directory listing.
