### ISSUE TITLE
Rewrite Plugin configs to irc3-style config.ini

### ISSUE THREAD

**Issue by mkzero** [Bytespeicher/Bytebot#148]
Existing plugin configuration should be converted to the ini-style config irc3 uses natively. 

An example plugin configuration could look like:

``` ini
[plugins.pluginname]
option1 = true

option2 = Lorem Ipsum

option3 =
    1
    2
    3

option4 = 12345
```

You can access those options from the code via the following code

``` python
# Set the default options
config = {
    option1 = False,
    option2 = "Lorem Ipsum",
    option3 = [1, 2, 3, 4, 5],
    option4 = 12345
}
config.update(self.bot.config.get(__name__, {}))

# You can access an option like this
option1 = config['option1']
```

**Comment by mape2k** [comment]
I've tried this, but it didn't work (config not defined). Do i have to import any irc3 module?

**Comment by mkzero** [comment]
If you're in a definiton, not a class method, you might want to remove the `self` from the `self.bot.config`

**Comment by mape2k** [comment]
Test it successfull ;) Working on these changes now for all plugins...
