### ISSUE TITLE
Creating a chromecast plugin

### ISSUE THREAD

**Issue by jurkov** [Bytespeicher/Bytebot#154]
Do we want a plugin to control our chromecast?
We could use https://github.com/balloob/pychromecast

**Comment by mape2k** [comment]
Control a local device via IRC will be annoy local users. We should not control such infrastructure remote.

**Comment by mkzero** [comment]
Not to mention that those cast APIs are AFAIK only available to the local domain, e.g. we'd have to create a connection between our server and our local NAT net.. I don't think that's a practical thing.

I'd rather continue the general project of space automation with a local device. I'll close this issue but we could think about using that lib on our local RPi(the one that creates the temperature stats for the spaceapi)
