### ISSUE TITLE
Bot will be kicked if a plugin sends too many messages at once

### ISSUE THREAD

**Issue by mkzero** [Bytespeicher/Bytebot#41]
If the bot is started the first time with e.g. the RSS reader plugin configured, it will be kicked for excess flooding as it tries to send all messages at once without any rate-limit. Messages from the bot should always be rate-limited. If a plugin tries to send too many messages at once this should trigger a warning and drop any messages above a certain message count.

**Comment by mkzero** [comment]
Will be solved with #111

**Comment by mape2k** [comment]
ACK
